### PR TITLE
feat: add CLI command

### PR DESCRIPTION
**Pull request by ChristianGiupponi**
This PR add the support for WP CLI.  
It adds a new command `wp flush-opcache flush` that tries to flush the cache.

### CODE REVIEW

**Comment by nierdz** [comment]
Thanks, this PR is perfect !

Could you just please change the title commit to `feat: add CLI command` as this is used in automatic changelog ?

**Comment by ChristianGiupponi** [comment]
> Thanks, this PR is perfect !
> 
> Could you just please change the title commit to `feat: add CLI command` as this is used in automatic changelog ?

Done!

**Comment by nierdz** [comment]
I was talking about the commit title, not the PR.

**Comment by ChristianGiupponi** [comment]
> I was talking about the commit title, not the PR.

ok sorry, could you tell me how? I have no idea about how to edit it

**Comment by nierdz** [comment]
> > I was talking about the commit title, not the PR.
> 
> ok sorry, could you tell me how? I have no idea about how to edit it

You need to use git interactive rebase. Here is a very smal step by step to do it from your repository (the cloned one)

1. `git checkout features/add-cli-command`
2. `git rebase -i master`
3. You change the commit by adding `r` letter before your commit
4. You will then have a prompt to change this commit
5. `git push --force-with-lease origin features/add-cli-command`

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

Or you can tick an option in this PR to allow maintainer (me) to make modifications on it and I'll do it myself.

**Comment by nierdz** [comment]
Hey @ChristianGiupponi

I just cherry-pick your commit in #44 to keep your authoring on this commit and did some minor modifications to make it compliant with `phpcs` tests. Thanks again, I'll release this 4.2.0 as soon as the CI is OK.
I close this PR.

**Comment by ChristianGiupponi** [comment]
Sorry for the delay but I had a very busy week!  
Glad to see it merged!

**Pull request closed without merging**
